languageCode = 'en-us'
title = 'Tech Medley'
theme = 'mini'
defaultContentLanguage = 'en'

[permalinks]
  [permalinks.page]
    posts = '/posts/:year/:month/:day/:slug/'

[markup]
    [markup.highlight]
        style = 'emacs'
    [markup.tableOfContents]
        endLevel = 3
        ordered = false
        startLevel = 2

[social]
    github = 'https://github.com/helkhalfi'
    linkedin = 'https://www.linkedin.com/in/helkhalfi/'

[params]
    author = 'Hichame El Khalfi'
    bio = 'Software Engineering Medley'
    description = 'Software Engineering Medley'
    hiddenPostSummaryInHomePage = true
    showToc = true
